# Загрузка и объединение данных

Ноутбук выполняет загрузку данных из всех источников и их объединение:

1. **Ручная разметка** — `dataset.json` + экспорты чатов (ham)
2. **lols.bot** — `parsed_lols_2024.txt` + `parsed_lols_2025_2026.jsonl` (spam)
3. **Незарегистрированный спам** — из SQLite базы бота

После объединения проверяются конфликты меток и результат сохраняется в `data/interim/raw_combined.csv`.

## Импорт необходимых библиотек

Используются `pandas`, `numpy` и модули проекта:
- `src.data.loaders` — загрузка JSON и TXT файлов
- `src.data.preprocessing` — предобработка текста
- `src.features.extractors` — извлечение числовых признаков
- `src.config` — пути к директориям данных

In [1]:
import json
import os
import re
import sqlite3
import sys
import numpy as np
import pandas as pd

try:
    _project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    _cwd = os.getcwd()
    _project_root = _cwd
    while _project_root != '/' and not os.path.isdir(os.path.join(_project_root, 'src')):
        _project_root = os.path.dirname(_project_root)
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from src.data.loaders import load_json, load_txt_lines
from src.data.unregistered_spam import extract_unregistered_spam
from src.data.preprocessing import preprocess_text, normalize_unicode, strip_html
from src.features.extractors import (
    count_emojis,
    count_newlines,
    count_whitespaces,
    count_links,
    count_tags,
    capital_ratio,
    count_punctuation,
    count_digits,
    avg_word_length,
    word_count,
    unique_word_ratio,
    repeat_char_ratio,
    count_phone_numbers,
    has_crypto_mention,
    count_exclamation,
    url_ratio,
    count_html_tags,
    has_markdown_formatting,
    emoji_diversity,
)
from src.config import RAW_DIR, EXTERNAL_DIR, INTERIM_DIR, PROCESSED_DIR, PROJECT_ROOT, CHAT_EXPORTS_DIR

from copy import deepcopy

## Первичная подготовка данных

Данные собираются из четырёх источников и объединяются в один датафрейм.

### Чтение файлов подготовленных вручную

Источники с ручной разметкой: `dataset.json` (чат "ЧАТ_СТАНКИН Абитуриент")

`data/dataset.json` – `.json` файл структуры `[{"text": "blablabla", "label": 0}]`, где ключ `text` представляет текстовое значение сообщения, а ключ `label` – класс сообщения (0: безопасное, 1: опасное).
Сообщения были собраны из самого чата "ЧАТ_СТАНКИН Абитуриент".

In [2]:
_dataset_path = RAW_DIR / 'dataset.json'
df_manual = pd.read_json(_dataset_path)
new_records = []
for _subdir in sorted(os.listdir(CHAT_EXPORTS_DIR)):
    _result_path = os.path.join(CHAT_EXPORTS_DIR, _subdir, 'result.json')
    if not os.path.exists(_result_path):
        continue
    with open(_result_path, 'r', encoding='utf-8') as _f:
        _data = json.load(_f)
    for _msg in _data.get('messages', []):
        if _msg.get('type') == 'service':
            continue
        _text_entities = _msg.get('text_entities')
        if _text_entities:
            _msg_text = ''.join((e.get('text', '') for e in _text_entities))
        elif isinstance(_msg.get('text'), str):
            _msg_text = _msg['text']
        else:
            continue
        _msg_text = _msg_text.strip()
        if _msg_text:
            new_records.append({'text': _msg_text, 'label': 0})
if new_records:
    df_new = pd.DataFrame(new_records)
    df_manual = pd.concat([df_manual, df_new], ignore_index=True)
    print(f'Добавлено {len(new_records)} сообщений из экспортов чатов')
    print(f'Всего в dataset.json (в памяти): {len(df_manual)} строк')
    print('Запись на диск — после проверки конфликтов меток')
else:
    print('Нет новых сообщений из экспортов чатов')

Добавлено 98010 сообщений из экспортов чатов
Всего в dataset.json (в памяти): 245696 строк
Запись на диск — после проверки конфликтов меток

In [3]:
df_manual.head()

                                                text  label
0  Добрый день! Отличается ли перечень необходимы...      0
1              Узбекистан. Рассматриваются обе формы      0
2  Здравствуйте, а как проходит поступление после...      0
3                          Спасибо большое за ответ!      0
4  Здравствуйте, а когда будет день открытых двер...      0

### Чтение файлов, предоставленных сторонними ресурсами

Внешний источник спам-сообщений: lols.bot.

#### LOLS Bot Data 2024

`data/parsed_lols_2024.txt` – `.txt` файл с набором спам-сообщений.
Файл был получен с [lols.bot](https://lols.bot/2024/)

In [4]:
parsed_lols_2024 = load_txt_lines(EXTERNAL_DIR / 'parsed_lols_2024.txt')

Базовая очистка: первый <br/> убирается, остальные заменяются на \n

In [5]:
for _i in range(len(parsed_lols_2024)):
    parsed_lols_2024[_i] = parsed_lols_2024[_i].replace('<br/>', '', 1).strip().replace('<br/>', '\n')

In [6]:
len(parsed_lols_2024)

34381

In [7]:
df_lols_2024 = pd.DataFrame()
df_lols_2024['text'] = parsed_lols_2024
df_lols_2024['label'] = [1] * len(parsed_lols_2024)

In [8]:
df_lols_2024.head(3)

                                                text  label
0  Нужны срочно ребятa нa офис 8000 4-6чaсов сроч...      1
1  Нужeн пoмoщник нa cклaд зп в день от 3000pyб п...      1
2  🔤🔤🔤🔤🔤🔤<br><br>      НЕТ 18 ЛЕТ — НЕТ ДЕНЕГ <br...      1

#### LOLS Bot Data 2025–2026

`data/external/parsed_lols_2025_2026.jsonl` – `.jsonl` файл с набором спам-сообщений за 2025 год и первое полугодие 2026 года.
Файл был получен с [lols.bot](https://lols.bot/) с помощью скрипта `scripts/parse_lols.py`.
Каждая строка содержит JSON с полями `id`, `datetime`, `uid`, `text`, `category`.

In [9]:
_lols_2025_2026_path = EXTERNAL_DIR / 'parsed_lols_2025_2026.jsonl'
df_lols_2025_2026 = pd.read_json(_lols_2025_2026_path, lines=True)

Извлечение текста и приведение к виду `['text', 'label']`. Пустые тексты отфильтровываются.

In [10]:
df_lols_2025_2026 = df_lols_2025_2026[['text']].dropna()
df_lols_2025_2026 = df_lols_2025_2026[df_lols_2025_2026['text'].str.strip() != '']
df_lols_2025_2026['label'] = 1

In [11]:
len(df_lols_2025_2026)

50121

In [12]:
df_lols_2025_2026.head(3)

                                                text  label
0                             Ben küfürden atilmadim      1
1  название — 𝗖𝗔𝗥𝗔 𝗩𝗘𝗦𝗣𝗔 (моно)\nинфо — https://t...      1
2  🆚 𝐔𝐍𝐊𝐍𝐎𝐖𝐍 𝐧𝟓-𝟔🇺🇿\n1:1 на уважения💕АРХИВ)\n💬 ht...      1

### Извлечение незарегистрированного спама

Выявляются спам-сообщения, которые были удалены из чата вручную
модераторами, но не были пойманы ботом автоматически.

Алгоритм:
1. Берутся все сообщения, которые бот видел (таблица `collected_message`).
2. Из них вычитаются сообщения из всех экспортов чатов (остались в чате = безопасные).
3. Вычитаются сообщения из таблицы `spam_message` (уже пойманный спам).
4. Остаток — сообщения, удалённые вручную, с высокой вероятностью являющиеся спамом.

Если файл `data/interim/unregistered_spam.json` уже существует,
он загружается без перезаписи (для ручной проверки и редактирования).
Иначе файл создаётся автоматически.

In [13]:
BACKUPS_DIR = os.path.join(PROJECT_ROOT, 'instance', 'backups')
_backup_files = sorted(
    [f for f in os.listdir(BACKUPS_DIR) if f.endswith('.sql')],
    reverse=True,
) if os.path.isdir(BACKUPS_DIR) else []
DB_PATH = os.path.join(BACKUPS_DIR, _backup_files[0]) if _backup_files else None
UNREGISTERED_OUTPUT = EXTERNAL_DIR / 'unregistered_spam.json'
if DB_PATH:
    print(f'Бэкап: {DB_PATH}')
else:
    print('Бэкап не найден в instance/backups')

Бэкап: /home/sophrosyne/STANKIN_AntiSpam_Bot/instance/backups/backup_20260704_160003.sql

In [14]:
df_unregistered = pd.DataFrame(columns=['text', 'label'])

In [15]:
_unregistered_from_backup = False
if os.path.exists(UNREGISTERED_OUTPUT):
    df_unregistered_1 = pd.read_json(UNREGISTERED_OUTPUT)
    if 'label' not in df_unregistered_1.columns:
        df_unregistered_1['label'] = 1
    print(f'Загружено из существующего файла: {len(df_unregistered_1)} строк')
elif DB_PATH and os.path.exists(DB_PATH):
    _manual_texts = set(df_manual['text'].tolist())
    df_unregistered_1 = extract_unregistered_spam(DB_PATH, CHAT_EXPORTS_DIR, _manual_texts)
    _unregistered_from_backup = True
else:
    df_unregistered_1 = pd.DataFrame(columns=['text', 'label'])
    print('Бэкап и файл не найдены — пропускаем')
print(f'\nИтого незарегистрированного спама: {len(df_unregistered_1)} строк')

Загружено из существующего файла: 47 строк

Итого незарегистрированного спама: 47 строк

Интерактивная проверка незарегистрированного спама.

Если файл `unregistered_spam.json` не существовал и данные были извлечены из бэкапа, каждое сообщение выводится по очереди. Ввод `y` — подтверждает спам, `n` — переносит в `df_manual` как безопасное (label=0). После проверки результат сохраняется в файл.

In [16]:
if _unregistered_from_backup and len(df_unregistered_1) > 0:
    _keep_texts = []
    _moved_to_ham = 0
    for _i, _row in df_unregistered_1.iterrows():
        print(f'[{_i + 1}/{len(df_unregistered_1)}]')
        print(_row['text'][:300])
        _ans = input('Спам? (y/n): ').strip().lower()
        print()
        if _ans == 'n':
            df_manual = pd.concat(
                [df_manual, pd.DataFrame([{'text': _row['text'], 'label': 0}])],
                ignore_index=True,
            )
            _moved_to_ham += 1
        else:
            _keep_texts.append(_row['text'])
    df_unregistered_1 = pd.DataFrame(
        [{'text': t, 'label': 1} for t in _keep_texts]
    )
    with open(UNREGISTERED_OUTPUT, 'w', encoding='utf-8') as _f:
        json.dump(df_unregistered_1.to_dict('records'), _f, ensure_ascii=False, indent=2)
    print(f'Перенесено в ham: {_moved_to_ham}')
    print(f'Оставлено в спаме: {len(df_unregistered_1)}')
    print(f'Сохранено в {UNREGISTERED_OUTPUT}')
else:
    print('Интерактивная проверка пропущена')

Интерактивная проверка пропущена

### Объединение подходящих файлов

Все источники объединяются в один датафрейм `df`.
Перед объединением проверяются конфликты меток: если один и тот же
текст встречается с разными `label` в разных источниках — ячейка
выводит конфликты с указанием файла-источника и прерывает выполнение.

Также только после успешной проверки `dataset.json` записывается на диск
(с добавленными текстами из экспортов чатов).

In [17]:
print(f'До объединения: {len(df_manual)} строк')

До объединения: 245696 строк

In [18]:
df_manual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245696 entries, 0 to 245695
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   text    245696 non-null  object
 1   label   245696 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.7+ MB

In [19]:
df_manual['_source'] = 'dataset.json'
df_lols_2024['_source'] = 'parsed_lols_2024.txt'
df_lols_2025_2026['_source'] = 'parsed_lols_2025_2026.jsonl'
df_unregistered_1['_source'] = 'unregistered_spam.json'

Временное объединение для проверки конфликтов до создания df

In [20]:
_tmp = pd.concat([df_manual, df_lols_2024, df_lols_2025_2026, df_unregistered_1], ignore_index=True)
_tmp = _tmp[_tmp['text'].notna()]
_tmp = _tmp[_tmp['text'].str.strip() != '']
_tmp = _tmp[_tmp['text'].str.len() >= 3]

In [21]:
label_groups = _tmp.groupby('text')['label'].nunique()
conflicts = label_groups[label_groups > 1]

In [22]:
if len(conflicts) > 0:
    print(f'ОШИБКА: найдено {len(conflicts)} текстов с конфликтными метками!')
    print('Объединение отменено. Исправьте метки в исходных файлах и перезапустите ячейки до этой включительно.\n')
    for txt in conflicts.index:
        rows = _tmp[_tmp['text'] == txt]
        labels = rows['label'].tolist()
        sources = rows['_source'].tolist()
        preview = txt[:80].replace('\n', ' ')
        print(f'  "{preview}"')
        for lbl, src in zip(labels, sources):
            print(f'    label={lbl}  источник={src}')
        print()
    raise ValueError(f'Найдено {len(conflicts)} конфликтных меток. Исправьте исходные данные.')

Запись dataset.json на диск — только после успешной проверки конфликтов

In [23]:
_dataset_path = RAW_DIR / 'dataset.json'
_df_save = df_manual.drop(columns=['_source'], errors='ignore')
_df_save.to_json(_dataset_path, orient='records', force_ascii=False, indent=2)
print(f'dataset.json записан: {len(_df_save)} строк')

dataset.json записан: 245696 строк

In [24]:
df = pd.concat([df_manual, df_lols_2024, df_lols_2025_2026, df_unregistered_1], ignore_index=True)
print(f'Всего строк: {len(df)} (из них незарегистрированного спама: {len(df_unregistered_1)})')

Всего строк: 330245 (из них незарегистрированного спама: 47)

## Сохранение объединённого датасета

Результат сохраняется в `data/interim/raw_combined.csv` для использования в следующем ноутбуке.

In [25]:
INTERIM_DIR.mkdir(parents=True, exist_ok=True)
df.to_csv(INTERIM_DIR / 'raw_combined.csv', index=False)
print(f'Сохранено: {len(df)} строк в {INTERIM_DIR / "raw_combined.csv"}')

Сохранено: 330245 строк в /home/sophrosyne/STANKIN_AntiSpam_Bot/data/interim/raw_combined.csv