# Создание обработанного датасета

## Импорт необходимых библиотек

In [1]:
import json
import os
import numpy as np
import pandas as pd

from langdetect import detect  # для создания выборок сообщений на русском языке

import emoji
import regex
import re

from copy import deepcopy

## Первичная подготовка данных

### Чтение файлов подготовленных вручную

`data/dataset.json` – `.json` файл структуры `[{"text": "blablabla", "label": 0}]`, где ключ `text` представляет текстовое значение сообщения, а ключ `label` – класс сообщения (0: безопасное, 1: опасное).  
Сообщения были собраны из самого чата "ЧАТ_СТАНКИН Абитуриент".

In [2]:
df_manual = pd.read_json('../data/dataset.json')

In [3]:
df_manual.head()

                                                text  label
0  Добрый день! Отличается ли перечень необходимы...      0
1              Узбекистан. Рассматриваются обе формы      0
2  Здравствуйте, а как проходит поступление после...      0
3                          Спасибо большое за ответ!      0
4  Здравствуйте, а когда будет день открытых двер...      0

`data/dataset_discord.json` – `.json` файл структуры `[{"text": "blablabla", "label": 0}]`, где ключ `text` представляет текстовое значение сообщения, а ключ `label` – класс сообщения (~~0: безопасное~~, 1: опасное).  
Сообщения были собраны из чатов Discord* сервера.  

> _Discord* – запрещенная социальная сеть в Российской Федерации._

In [4]:
df_discord = pd.read_json('../data/dataset_discord.json')

In [5]:
df_discord.head()

                                                text  label
0  # _**Лучший спам-бот!!! **_\n**залетай к нам н...      1
1  Лучший кряк нурсултана! https://wdfiles.ru/1tf...      1
2  https://oxy.name/d/pddi я заболел раокм гамна ...      1
3  Забирайте S.T.A.L.K.E.R 2 предзаказ на свой St...      1
4  https://only-fans.uk/morphe_ya\nOnlyFans UK - ...      1

### Чтение файлов, предоставленных сторонними ресурсами

#### Umputun's tg-spam Dataset

`data/spam_samples_umputun.txt` – `.txt` файл с набором спам-сообщений.  
Файл был получен с [umputun/tg-spam GitHub](https://github.com/umputun/tg-spam/tree/master/data)

In [6]:
spam_tg_umputun = open('../data/spam_samples_umputun.txt', 'r', encoding='utf-8').readlines()

In [7]:
for i in range(len(spam_tg_umputun)):
    spam_tg_umputun[i] = spam_tg_umputun[i].strip().rstrip()

In [8]:
spam_tg_umputun

["Use this link and register your account now start earning in cryptocurrency and testify to others Https://accetgrowth.ltd Use this link and register your account now start earning in cryptocurrency and testify to others https://tinyurl.com/yrd86r5b Your investment is safe and secure with this transparent and legit platform https://tinyurl.com/yrd86r5b Don't miss this opportunity to earn with this platform and be financially stable click on the link to join https://urlz.fr/orYP Trusted and legit investment platform no hidden charges https://tinyurl.com/yrd86r5b",
 'Globalstockoptions is one of the best trade broker trade platform I have been trading with them more than 9 months and I have got withdrawal ib commission more than $350000, I have more than 250 plus clients today those trading with Globalstockoptions and best part no one is calling me for any issues or not even for any update. I am so grateful and thankful to Globalstockoption, finally we have broker who do not have issues with withdrawal, you can contact their agent on the link below   https://t.me/+dGA3mE_zk-EwZThk Globalstockoptions is one of the best trade broker trade platform I have been trading with them more than 9 months and I have got withdrawal ib commission more than $350000, I have more than 250 plus clients today those trading with Globalstockoptions and best part no one is calling me for any issues or not even for any update. I am so grateful and thankful to Globalstockoption, finally we have broker who do not have issues with withdrawal, you can contact their agent on the link below   https://t.me/+ADkftV98dXg1NTlk',
 "Now I believe in what people say about you is true, You're indeed a Man of your words , you have changed lives including mine with just Investment of $400 I make withdrawal of $8000 thanks for your kindness Sir , I will use this opportunity to recommend you to everyone here. Click on the link below",
 'https://t.me/+jS6cJeri0ug5MDkx   This is very legitimate and wonderful ,I know  everyone here has witnessed that this platform is 100% confidential',
 "Investing in a genuine company with great investment profits is the best thing any investor could ever do. I am fortunate to have discovered this company and they have been my major source of income. They are 100% GENUINE and trusted with successful payout https://t.me/+a2CESJk_nm1mYjE8  https://t.me/+a2CESJk_nm1mYjE8 You've surprised me again with $15,000 just after 3 days which I made with the initial investment capital of $800 I've all cast to be thankful, I never believed I could make such huge profits in a few days through Forex trading, thank you so much for sincerity for expert experience, I'll keep on spreading your good work, click on the link below to connect",
 'This is very legitimate and wonderful ,I know  everyone here has witnessed that this platform is 100% confidential',
 "All thanks to your good work sir  https://t.me/+X4_xs3XKM3o2MzRk https://t.me/+X4_xs3XKM3o2MzRk If you're still depending on your salaries, you're one step away from poverty. Don't let your fears get the best of you because fear is just an illusion that stands between you and your success. I was down financially at a point of debt until i was introduced to this genuine platform where I have been making money, I have made up to 11,000 USD already and my life took a better turn, i highly recommend you to join and start making daily income without risks",
 '😍 Biggest Mega Lifafa Giveaway\xa0  Claim & Share 🔥  ✅ Link :  https://infotecharmy.in/lifafa?id=3MucT2z  🎁 Per User : ₹40/-\xa0 ✅  💛Access Code :- EARN40₹  🔴NOTE  MUST JOINED CHANNEL FOR CLIAM LIFAFA ❤️  Claim Fast ~ Share With Friends And Family ~\xa0 And Pin To Top ~ Enjoy 🥳',
 "It's has been a fruitful moment for me ever since I started my investment  in Optic -trade .this platform has been helpful to me in grow my coin and also with a fast method of withdrawal with zero fees.  Anyone interested can use the link below for more clearifications.  https://lanza.me/2cxR",
 'Hello brothers! This is an investment company I came across recently and they pay me a really great amount. https://advanced-earners.com',
 "I have no hesitation in highly recommending Catherine  Why not use your 5 to 6 hour's to work from home while waiting for your salary  5 people are needed in this group to come and work online , to earn $5,520 in 2 business days Join Group 👇👇👇",
 'Registration fee:00$ www.spacexminer.ltd Daily earnings:✅ No problem ❌ Use my referral and get free bonus  the “LINK below',
 'Invest in this company for a bright future - their solid industry reputation, strong cash reserves, and steady dividend payouts make them an ideal choice for income-oriented investors',
 "Wow I just made 5600usd with just 500usd Working with Annie is really profitable  I've been receiving huge win since I came in contact with him She doesn't ask for hidden charges or additional fees like others he is 💯 legit Click on the link below to connect with him",
 '🔥🔥🔥$30,000 FLOXY FEST   🌟Floxypay is an all-in-one platform that offers a decentralized wallet and it’s having many ongoing campaigns to give out huge rewards to its communities, attracting new users.  Check out the following about how to join the campaigns and share $30,000!🎁',
 "Drop your wallets for 0.5 ETH🔷  winner announcement after 12 hours Drop your wallet for 50$ invite your 1 friend and write done I'm looking for a new project👑  Shill me 🔶🔷 Drop your wallet Drop your wallet for 20$  5 lucky winner 🏆 Drop your wallet for 10$  12 lucky winner 🏆 Today's my birthday so I'm doing for discount for every call   Today's call charge : 20$  Dm me for call Today is the second day of my birthday  So I will give you a special discount on my call🔶🔷  Dm me for call Drop your wallet for 20$  4 lucky winner 🏆  Promo calls for your budget ✅",
 'Share your 10X #altcoin or #NFT recommendations',
 "Drop your wallet for 1 ETH  Today is my birthday I will reward the one who will say good things to me Shill me your good coins🔹🔸 Hey everyone ❤️  Shill me your gems🔹🔸 I'm looking for a new project   Shill me 🔶🔷 I'm looking for a new project   Shill me 🔹🔶 I'm looking for a legit project   DM me 🔹🔶",
 "Don't miss out on the immense potential of this company - their disruptive business model, growing customer base, and visionary leadership make them an excellent investment prospect. https://advanced-earners.com This is a stable and lucrative investment opportunity.",
 "I have no hesitation in highly recommending Catherine  Why not use your 5 to 6 hour's to work from home while waiting for your salary  5 people are needed in this group to come and work online , to earn $5,520 in 2 business days Join Group 👇👇👇",
 "I started with doubts but I have received my payment I'm 100% sure it’s real, I got $18,500 after investing $600 here's the company Link Below",
 'Get 100% profit in 24 hours no scam no delay free registration free withdrawal',
 "ou made me to trust you and you never failed me, this will help in taking care of my family. GOD BLESS you , you cleared my doubts ☺️👏I’m so grateful 🥹 I will share my testimony to the world so they can see and benefit from you, I love your words of encouragement and your sense of understanding,  you're Great 😊  Thank's ma'am Lisa for turning my $300 to $5000  I’m grateful. Thanks for your amazing business offer ☺️🤍  Follow her below 👇👇",
 "I'm only doing this with out of joy UPRISE trading has proven to me that real companies still exist till today",
 'Floxypay is an all-in-one platform that offers a decentralized wallet and it’s having many ongoing campaigns to give out huge rewards to its communities, attracting new users.  Check out the following about how to join the campaigns and share $30,000!🎁',
 "Hello! 👋  Want to effortlessly locate new clients just like I do? 🚀 I've got a one-of-a-kind instrument that can aid you with that! 🎯  This special program works while you relax. It operates from your computer and autonomously searches for people who might be curious in what you provide. 🖥️💡  To start using it, simply tap the hyperlink below and register. 🎁⬇️  https://capital-hub.ltd/?ref=Sandraelina1  After registering with the platform, you write to our support team. This will give you permission to a confidential communication with advice on how to earn, as well as a $10 bonus on your funds for an successful launch. 💵💬  Don't procrastinate what can result in you achievement today! 🚀👍 After setup, be sure to get in touch with us for bonuses and accurate application settings. Contact details can be found in the file.",
 "All thank to  @Beyondtrader for the successful cash out. I am really grateful to you for the help and the love you've shown me. 👉 https://t.me/trade_with_jamasmolly",
 '🗣 Believe in yourself everyday, always know that\xa0 there is no limits to what you can achieve.  Why not use your 5 to 6 hours to learn how  forxe trading market , work while waiting for your salary  5 people are needed in this group to come and  learn forxes trading market online , to earn $5,520 in 2 business days if interested ask how ⬇️⬇️⬇️ https://t.me/JION_Chat_FOREX_TRADAR_INVEST 🗣 Believe in yourself everyday, always know that\xa0 there is no limits to what you can achieve.  Why not use your 5 to 6 hours to learn how  forxe trading market , work while waiting for your salary  5 people are needed in this group to come and  learn forxes trading market online , to earn $5,520 in 2 business days if interested ask how ⬇️⬇️⬇️ https://t.me/+wrM82HHN6jllNmI8',
 'LAUNCHING IN 3MINUTES AT BSC NETWORK (18UTC)  I ALREADY PAID 3MASSIVE INFLUENCERS. MORE INFLUENCERS GOING TO PAY LATER AND WILL ANNOUNCE IT HERE AT THIS CHANNEL  WE MIGHT BE POSTED AT @BSCTRENDING, IM JUST WAITING FOR THE ADDRESS OF OWNER.  GET READY, LAUNCH INCOMING!',
 "Investing can be a daunting task, but Advanced Earners makes it easy. Their user-friendly platform and knowledgeable staff make it easy to get started, and their investment options are tailored to meet your specific needs and goals. If you're looking to grow your wealth, I highly recommend checking them out https://advanced-earners.com/",
 "Hello everyone, I've found an investment platform that's the real deal. It's legit, pays out, and can help us grow our money. Let's seize this opportunity together.",
 "Crypto exchange help alot With a little deposit of $300 i earn over $4,000 within a short period of time.. I just can say how happy I'm right now thanks so much sir for your help and support.. I'm so grateful sir.. You can contact him on the link below",
 "Hello travel lovers in this group! I've come across an unbelievable opportunity for us to explore the beautiful beaches of Bali at a fraction of the usual cost. This all-inclusive package includes flights, luxury accommodation, and exclusive tours. It's a limited-time offer, so we need to act fast. Don't miss out on this dream vacation. For more details and to grab this deal, check out this link. Let's make unforgettable memories together!",
 "Attention all group members! I'm excited to share that our community has been specially chosen for a sneak peek at an innovative new product line that's set to revolutionize the tech world. We're talking cutting-edge gadgets at an introductory price that's just too good to pass up. But that's not all – as early adopters, you'll also have a say in future developments. Click here to be among the first to experience this game-changing technology and help shape its future.",
 "Calling all fitness buffs in the group! We're launching a 30-day fitness challenge that's not just about getting in shape but also about building a community of like-minded individuals who support and motivate each other. Whether you're a beginner or a pro, there's something for everyone. Plus, there are weekly prizes and a grand prize for the most transformative journey. Don’t wait! Sign up here and let’s embark on this journey to fitness together. Remember, the only bad workout is the one you didn't do!",
 "Big news for everyone in this group! We just got our hands on a bunch of tickets for the hottest event of the year, and we're giving them away to you, our amazing group members. Imagine a night of incredible music, amazing food, and fantastic company. To claim your free ticket, be among the first 50 to click on this link. Let's make it a night to remember!",
 "Hi everyone! We've noticed that many of you are keen on smart investment opportunities. We're introducing an exclusive group investment plan that promises not just great returns but also security and ease of management. This is your chance to get in on the ground floor of something big. Don't let this opportunity slip away. Learn more and join our growing group of savvy investors here. Let's grow our wealth together!",
 "Great news for everyone in here! We've partnered with a leading electronics brand to offer our group an exclusive discount on the latest smartphones. This deal is way too good to miss, and it's just for us! Head over to this link to grab your new phone at a never-seen-before price. Remember, it's a limited-time offer, so better be quick!",
 "Attention all foodies! We've managed to secure a special group discount at the hottest new restaurant in town. This is your chance to taste exquisite dishes crafted by a renowned chef. Reserve your table through this link and indulge in a culinary adventure. Let's turn this into a group outing to remember!",
 "Hey, group members! Are you tired of the same old fitness routines? We've teamed up with a top-notch gym to bring an exclusive group fitness session with celebrity trainers. This is a fantastic opportunity to get fit and have fun as a group. Sign up here and let's sweat it out together!",
 "Exciting update for everyone! We're organizing a group trek to the scenic mountains next month. It's going to be an adventure filled with breathtaking views and exhilarating hikes. Spots are limited, so make sure to register quickly through this link. Let's conquer the peaks together!",
 "Hello, creative minds! We're thrilled to announce a group art exhibition and your work could be featured! This is a fantastic platform to showcase your talent and connect with fellow artists. Submit your artwork here and let's make this event a grand success.",
 'Calling all tech enthusiasts! Join us for an exclusive webinar on the latest trends in technology, featuring industry experts. This is a great opportunity to learn, network, and stay ahead in the tech world. Register here and be part of this enlightening experience.',
 "Special announcement: Our community is invited to a private screening of an award-winning documentary film. This is a rare chance to see a masterpiece and engage in a discussion with the filmmakers. Book your seats here and let's enjoy a night of cinema together!",
 "Group members, get ready for a surprise! We're planning a secret flash mob in the city center, and you're all invited to participate. It's going to be an epic event that will bring smiles and joy. Sign up here to be part of this fun and exciting activity!",
 "Dear group, we're launching a charity drive to support a local shelter. Your contributions can make a huge difference in people's lives. Please donate here and help us reach our goal. Every little bit counts, and together, we can bring about positive change.",
 "Hey everyone, we're hosting a group gaming night this weekend with some exciting multiplayer games. It's a perfect way to unwind and connect with fellow gamers. Join us by signing up here, and let's have a blast together!",
 "$FORG 24k mc, safe dev & good time to buy💎  https://www.dextools.io/app/en/ether/pair-explorer/0xe3b85d8adb87628c2a274e2e909de6e87785fed8  join🚀 https://t.me/Forg_Official $JEET🚨 project will launch in 4 days, the dev has excellent past projects and spends a lot on marketing, the launch will be stealth, i'll check for a entry  Telegram: https://t.me/SlaptheJEET $KIMOCAT aped solana play, now 5k mc  https://www.dextools.io/app/en/solana/pair-explorer/52p7Uqevx93Cyh3DPSnPc4BLFvap2pTdgmAmrrvJzWoD",
 '#техникаречи #ораторскоемастерство Привет! Преподаю технику речи, ставлю голос и исправляю речевые дефекты. Учу самостоятельно работать с материалом. Всё что может вам пригодиться, если вы, например, создаете собственный видеоконтент. Первое пробное занятие я провожу бесплатно. https://vmeste.info/anouncements/details2?ansid=2f6be178-5875-4f4d-857c-b21bcf1df4d4 #техникаречи #ораторскоемастерство Привет! Преподаю технику речи, ставлю голос и исправляю речевые дефекты. Учу самостоятельно работать с материалом. Всё что может вам пригодиться, если вы, например, создаете собственный видеоконтент. Первое пробное занятие я провожу бесплатно. Я работаю со всеми клиентами. LGBTQ+ friendly😊 https://vmeste.info/anouncements/details2?ansid=2f6be178-5875-4f4d-857c-b21bcf1df4d4 #техникаречи #ораторскоемастерство Привет! Удаленно преподаю технику речи, ставлю голос и исправляю речевые дефекты. Учу самостоятельно работать с материалом. Всё что может вам пригодиться, если вы, например, создаете собственный видеоконтент. Стоимость занятия - 1800 рублей. Пробный урок - 1000 Я работаю со всеми клиентами. LGBTQ+ friendly https://vmeste.info/anouncements/details2?ansid=2f6be178-5875-4f4d-857c-b21bcf1df4d4',
 'Привет, дорогие!)  Наблюдая за ростом популярности Influence-маркетинга — волей-неволей веришь в его волшебную силу.   Блогеры уже не просто контентмейкеры — они предприниматели.   И предпринимают всё, чтобы другие предприниматели тоже могли развивать свой бизнес через нативную рекламу и личные авторитетные рекомендации. ⠀ Цели тут могут быть разные: от поиска новых подписчиков до конкретных KPI в продажах.   Но тренд на привлечение блогеров для продвижения — вряд ли затухнет в ближайший десяток лет.  ⠀ 🔥 Мы нашли для вас полезного бота и чат для покупки такой рекламы: https://t.me/proinstar  Арина создала удобный сервис для сотрудничества с блогерами. Она уже 7 лет работает в рекламе у блогеров и имеет государственное образование «Реклама и PR», что большая редкость в нынешнее время.   Смысл в том, что вы платите за рекламу у качественных проверенных блогеров с отзывами и можете подобрать под свою целевую аудиторию.  ⠀ Все что нужно для старта — упаковать аккаунт, и выбрать нужных блогеров в боте. Бот ищи в закрепленных сообщениях чата.  ⠀ А в канале «Не Арина» (https://t.me/smmprostar) можно подсмотреть и подслушать, как правильно продвигаться с помощью социальных сетей и рекламы у блогеров э.   👉🏽 Поизучать бота можно здесь: https://t.me/proinstar Привет, дорогие!)',
 '♨️ Выигрышная серия: 199 + | 4 - (11 дней) LIVE Футбол Молодежная лига УЕФА Нант (19) - Лех Познань (19) Ставим строго на Тотал: https://t.me/yoolbet',
 '💢 Крушим Букмекера: 203 + | 4 - (12 дней) LIVE Футбол Лига Чемпионов АФК Бурирам Юнайтед - Мельбурн Сити Ставка на тотал: https://t.me/mitebet',
 '!!! ЗАРАБОТОК!!!  👍!!! БЕЗ ВЛОЖЕНИЙ!!! 👍 !!! ЗАОДНО И ОТДЫХ!!!  https://madrunning.page.link/mu72  Вы поклонник мобильных игр? Вы любите играть в игры, зарабатывая немного дополнительных денег? Если да, то у нас есть для вас потрясающая игра! Представляем нашу новейшую мобильную игру, Mad Running - идеальное игровое приложение, которое позволяет вам играть в игры и зарабатывать деньги одновременно.С Mad Running вы можете наслаждаться разнообразными веселыми и захватывающими играми, зарабатывая при этом реальные деньги. Все, что вам нужно сделать, это загрузить приложение по ссылке, приведенной ниже, создать свою учетную запись и начать играть. Чем больше вы играете, тем больше денег сможете заработать! Ссылка для установки Android: https://madrunning.page.link/mu72',

Приведение таблицы (датафрейма) к виду `['text', 'label']`

In [9]:
df_tg_umputun = pd.DataFrame()
df_tg_umputun['text'] = spam_tg_umputun
df_tg_umputun['label'] = [1] * len(spam_tg_umputun)

In [10]:
df_tg_umputun.head()

                                                text  label
0  Use this link and register your account now st...      1
1  Globalstockoptions is one of the best trade br...      1
2  Now I believe in what people say about you is ...      1
3  https://t.me/+jS6cJeri0ug5MDkx   This is very ...      1
4  Investing in a genuine company with great inve...      1

#### LOLS Bot Data 2024

`data/parsed_lols_2024.txt` – `.txt` файл с набором спам-сообщений.  
Файл был получен с [lols.bot](https://lols.bot/2024/)

In [11]:
parsed_lols_2024 = open('../data/parsed_lols_2024.txt', 'r', encoding='utf-8').readlines()

In [12]:
for i in range(len(parsed_lols_2024)):
    parsed_lols_2024[i] = parsed_lols_2024[i].replace('<br/>', '', 1).strip().replace('<br/>', '\n')

In [13]:
len(parsed_lols_2024)

34383

In [14]:
df_lols_2024 = pd.DataFrame()
df_lols_2024['text'] = parsed_lols_2024
df_lols_2024['label'] = [1] * len(parsed_lols_2024)

In [15]:
df_lols_2024.head(3)

                                                text  label
0  Нужны срочно ребятa нa офис 8000 4-6чaсов сроч...      1
1  Нужeн пoмoщник нa cклaд зп в день от 3000pyб п...      1
2  🔤🔤🔤🔤🔤🔤<br><br>      НЕТ 18 ЛЕТ — НЕТ ДЕНЕГ <br...      1

### Объединение подходящих файлов

In [16]:
df = pd.concat([df_manual, df_tg_umputun, df_discord, df_lols_2024], ignore_index=True)

Подключение незарегистрированного спама (из 7. Извлечение незарегистрированного спама)

In [17]:
if os.path.exists('../data/unregistered_spam.json'):
    df_unregistered = pd.read_json('../data/unregistered_spam.json')
    df = pd.concat([df, df_unregistered], ignore_index=True)
    print(f"Добавлено {len(df_unregistered)} незарегистрированных спам-сообщений")

Добавлено 33 незарегистрированных спам-сообщений

In [19]:
print(f"До очистки: {len(df)} строк")

До очистки: 76909 строк

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76909 entries, 0 to 76908
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    76909 non-null  str
 1   label   76909 non-null  int64
dtypes: int64(1), str(1)
memory usage: 1.2 MB

### Очистка данных

#### Удаление пустых и слишком коротких текстов

In [21]:
df = df[df['text'].notna()]
df = df[df['text'].str.strip() != '']
df = df[df['text'].str.len() >= 3]

In [22]:
print(f"После удаления пустых/коротких (<3 символов): {len(df)} строк")

После удаления пустых/коротких (<3 символов): 72986 строк

#### Дедупликация

In [23]:
before_dedup = len(df)
df = df.drop_duplicates(subset='text', keep='first')

In [24]:
print(f"Удалено дубликатов: {before_dedup - len(df)}")
print(f"После дедупликации: {len(df)} строк")

Удалено дубликатов: 14157
После дедупликации: 58829 строк

#### Исправление конфликтных меток

In [25]:
label_groups = df.groupby('text')['label'].nunique()

In [26]:
conflicts = label_groups[label_groups > 1]

In [27]:
if len(conflicts) > 0:
    print(f"Найдено {len(conflicts)} текстов с конфликтными метками:")
    for txt in conflicts.index:
        labels = df[df['text'] == txt]['label'].tolist()
        preview = txt[:80].replace('\n', ' ')
        print(f"  \"{preview}\" -> метки: {labels}")
    df = df[~df['text'].isin(conflicts.index)]
    print(f"Конфликтные записи удалены. Осталось: {len(df)} строк")
else:
    print("Конфликтных меток не найдено")

Конфликтных меток не найдено

#### Удаление пересечений с тестовой выборкой (Data Leakage)

In [28]:
if os.path.exists('../data/test_clear.json'):
    df_test_clear = pd.read_json('../data/test_clear.json')
    test_texts = set(df_test_clear['text'].tolist())
    before_leak = len(df)
    df = df[~df['text'].isin(test_texts)]
    removed = before_leak - len(df)
    if removed > 0:
        print(f"Удалено {removed} текстов, пересекающихся с тестовой выборкой (data leakage)")
    print(f"После очистки: {len(df)} строк")

Удалено 329 текстов, пересекающихся с тестовой выборкой (data leakage)
После очистки: 58500 строк

In [29]:
if os.path.exists('../data/parsed_lols_2023.txt'):
    lines_2023 = open('../data/parsed_lols_2023.txt', 'r', encoding='utf-8').readlines()
    test_spam_texts = set(l.replace('<br/>', '', 1).strip().replace('<br/>', '\n') for l in lines_2023 if l.strip())
    before_leak = len(df)
    df = df[~df['text'].isin(test_spam_texts)]
    removed = before_leak - len(df)
    if removed > 0:
        print(f"Удалено {removed} текстов, пересекающихся с parsed_lols_2023 (data leakage)")
    print(f"После очистки: {len(df)} строк")

Удалено 303 текстов, пересекающихся с parsed_lols_2023 (data leakage)
После очистки: 58197 строк

#### Итоги очистки

In [30]:
df = df.reset_index(drop=True)

In [31]:
print(f"Итого после очистки: {len(df)} строк")
print(f"  Ham (0): {len(df[df['label'] == 0])}")
print(f"  Spam (1): {len(df[df['label'] == 1])}")
print(f"  Соотношение: {len(df[df['label'] == 1]) / len(df[df['label'] == 0]):.2f}")

Итого после очистки: 58197 строк
  Ham (0): 33729
  Spam (1): 24468
  Соотношение: 0.73

## Обработка данных

### Создание новых столбцов с числовыми данными

В спам сообщениях очень часто используются эмодзи, ссылки, теги (`@`), много новых строк (`\n`) и лишних пробелов, так что их количество в сообщении может играть большую роль в классификации сообщений

### Создание новых столбцов с числовыми данными

В спам сообщениях очень часто используются эмодзи, ссылки, теги (`@`), много новых строк (`\n`) и лишних пробелов, так что их количество в сообщении может играть большую роль в классификации сообщений

#### Функции для подготовки текста и дополнительных числовых данных

> Эти же функции находятся в `../utils/preprocessing.py`.

In [32]:
def count_emojis(text: str) -> int:
    """
    Считает количество эмодзи в тексте.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        int: Количество найденных эмодзи.
    """
    # Разбиваем текст на "графемные кластеры" (учитывая составные эмодзи)
    data = regex.findall(r'\X', text)
    # Считаем эмодзи
    emoji_counter = sum(emoji.is_emoji(word) for word in data)
    return emoji_counter

In [33]:
def count_newlines(text: str) -> int:
    """
    Считает количество символов новой строки (\n) в тексте.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        int: Количество символов новой строки.
    """
    # Подсчёт символов новой строки
    newline_count = text.count('\n')
    return newline_count

In [34]:
def count_whitespaces(text: str) -> int:
    """
    Считает количество последовательных пробелов (два или более) в тексте.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        int: Количество найденных последовательных пробелов.
    """
    # Считаем последовательности из двух и более пробелов
    extra_spaces_count = len(re.findall(r'\s{2,}', text))
    return extra_spaces_count

Регулярное выражение для ссылок

In [35]:
url_pattern = r'(https?://[^\s]+|www\.[^\s]+|[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(?:/[^\s]*)?)'

In [36]:
def count_links(text: str) -> int:
    """
    Считает количество ссылок в тексте.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        int: Количество найденных ссылок.
    """
    # Найти все ссылки в тексте
    links = re.findall(url_pattern, text)
    return len(links)

In [37]:
def count_tags(text: str) -> int:
    """
    Считает количество упоминаний (тегов) в тексте.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        int: Количество найденных тегов.
    """
    # Подсчёт символов "@" как маркеров тегов
    tag_count = text.count('@')
    return tag_count

Удаление пунктуации и эмодзи, приведение к нижнему регистру может снизить шум и сложность модели

In [38]:
def remove_emojis(text: str) -> str:
    """
    Удаляет все эмодзи из текста.

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        str: Текст без эмодзи.
    """
    # Разбиваем текст на "графемные кластеры"
    data = regex.findall(r'\X', text)
    # Удаляем все эмодзи
    text_without_emojis = ''.join(word for word in data if not emoji.is_emoji(word))
    return text_without_emojis

Ссылки и тэги без пунктуации превращаются в набор латинских символов, что будет мешать работе модели, но при этом их нельзя удалять из текстов, так как это важные маркеры. Поэтому их необходимо заменить на что-то вроде `[LINK]` и `[TAG]`

In [39]:
def replace_links(text: str) -> str:
    """
    Заменяет все ссылки в тексте на "[LINK]".

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        str: Текст с заменёнными ссылками.
    """
    # Заменить ссылки на [LINK]
    text = re.sub(url_pattern, '[LINK]', text)
    return text

In [40]:
def replace_tags(text: str) -> str:
    """
    Заменяет все упоминания (теги) в тексте на "[TAG]".

    Параметры:
        text (str): Исходный текст.

    Возвращает:
        str: Текст с заменёнными тегами.
    """
    # Регулярное выражение для тегов
    tag_pattern = r'@[a-zA-Z0-9_]+'
    # Замена тегов на [TAG]
    text = re.sub(tag_pattern, '[TAG]', text)
    return text

In [41]:
def preprocess_text(
        text: str,
        lower: bool = True,
        remove_punctuation: bool = True,
        remove_emoji: bool = True,
        remove_whitespaces: bool = True,
        remove_links: bool = True,
        remove_tags: bool = True
) -> str:
    """
    Предобрабатывает текст, включая нормализацию регистра, удаление пунктуации, эмодзи, ссылок, тегов и пробелов.

    Параметры:
        text (str): Исходный текст.
        lower (bool): Приводить ли текст к нижнему регистру (по умолчанию True).
        remove_punctuation (bool): Удалять ли пунктуацию (по умолчанию True).
        remove_emoji (bool): Удалять ли эмодзи (по умолчанию True).
        remove_whitespaces (bool): Удалять ли лишние пробелы (по умолчанию True).
        remove_links (bool): Удалять ли ссылки (по умолчанию True).
        remove_tags (bool): Удалять ли теги (по умолчанию True).

    Возвращает:
        str: Обработанный текст.
    """
    # Приведение текста к нижнему регистру
    if lower:
        text = text.lower()
    # Замена ссылок на [LINK]
    if remove_links:
        text = replace_links(text)
    # Замена тегов на [TAG]
    if remove_tags:
        text = replace_tags(text)
    # Удаление пунктуации
    if remove_punctuation:
        text = re.sub(r'[^\w\s]', '', text)  # Удаляет пунктуацию
        # Восстановление [LINK] после очистки пунктуации
        if remove_links:
            text = text.replace('LINK', '[LINK]')
        # Восстановление [TAG] после очистки пунктуации
        if remove_tags:
            text = text.replace('TAG', '[TAG]')
    # Удаление эмодзи
    if remove_emoji:
        text = remove_emojis(text)
    # Удаление лишних пробелов и символов новой строки
    if remove_whitespaces:
        text = re.sub(r'\s+', ' ', text).strip()
    return text

#### Подготовка текста и дополнительных числовых данных

In [42]:
df_preprocessed = deepcopy(df)

In [43]:
emojis_count = []
newlines_count = []
whitespaces_count = []
links_count = []
tags_count = []
length_list = []
capital_ratio_list = []
for text in df['text']:
    emojis_count.append(count_emojis(text))
    newlines_count.append(count_newlines(text))
    whitespaces_count.append(count_whitespaces(text))
    links_count.append(count_links(text))
    tags_count.append(count_tags(text))
    length_list.append(len(text))
    upper_count = sum(1 for c in text if c.isupper())
    capital_ratio_list.append(upper_count / max(len(text), 1))

In [44]:
df_preprocessed['emojis'] = emojis_count
df_preprocessed['newlines'] = newlines_count
df_preprocessed['whitespaces'] = whitespaces_count
df_preprocessed['links'] = links_count
df_preprocessed['tags'] = tags_count
df_preprocessed['length'] = length_list
df_preprocessed['capital_ratio'] = capital_ratio_list

In [45]:
df_preprocessed.head()

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio
0,Добрый день! Отличается ли перечень необходимы...,0,0,0,0,0,0,83,0.024096
1,Узбекистан. Рассматриваются обе формы,0,0,0,0,0,0,37,0.054054
2,"Здравствуйте, а как проходит поступление после...",0,0,0,0,0,0,147,0.040816
3,"Здравствуйте, а когда будет день открытых двер...",0,0,0,0,0,0,62,0.016129
4,"Здравствуйте, необходимо для посещения дня отк...",0,0,0,0,0,0,82,0.012195

In [46]:
texts = list(deepcopy(df['text']))
for text_i in range(len(texts)):
    temp = preprocess_text(texts[text_i])
    if not temp:
        temp = np.nan
    texts[text_i] = temp

In [47]:
texts

['добрый день отличается ли перечень необходимых документов для иностранных граждан',
 'узбекистан рассматриваются обе формы',
 'здравствуйте а как проходит поступление после колледжа внутренний экзамен или только егэ и возможно ли всё ещё поступление сразу на второй курс',
 'здравствуйте а когда будет день открытых дверей и во сколько',
 'здравствуйте необходимо для посещения дня открытым дверей гдето регистрироваться',
 'добрый день да необходимо пройти быструю регистрацию на сайте [LINK]',
 'лучшая специальность жаль с моими баллами не пройти',
 'было бы неплохо если бы прикладывались ссылки для просмотра результатов экзаменов',
 'здравствуйте не смог найти списки поступающих на сайте ещё не опубликованы спасибо',
 'теперь увидел спасибо а как часто списки обновляются',
 'подскажите где найти ранжированные списки поступающих этого года по основному конкурсу',
 'вопрос к поступающим абитуриентам какая ориентировка на подачу заявления на согласие в последний момент или как жду любых деловых комментариев и советов иван сергеевич был ответ в последнюю очередь насчет последнего момента с вами не согласен если все начнут подавать согласия в 1700 11 августа то 1запросы обрушат сайт университета 2 никто не узнает своего рейтинга до 12 августа приемная комиссия ночью не работает эффект будет обратнымникто не сорентируется в местах не будет реальной информации при крайнем времени подачи с уважением иван сергеевич',
 'а когда будут данные о зачислении в магистратуру',
 'добрый день подскажите пожалуйста когда будет выпущен приказ по направлению 380403 очнозаочная форма обучения',
 'здравствуйте если подано согласие но в конце дня оказывается что не прохожу по баллам переподать на другую группу уже не получится как тогда поступать',
 'день добрый а как теперь понять зачислен ли ты',
 'а когда закончится обработка и после ее окончания если мое место по согласия входит в количестве мест то я прохожу',
 'а когда закончится обработка',
 'приветствую вопрос прием согласий закончен списки есть 17 будет приказ а что дальше будет какоенибудь собрание для поступивших',
 'когда закончится обработка',
 'добрый день согласие на зачисление поданное через лк на сайте университета посредством нажатия кнопки это и есть официальное согласие скан подписанного заявления никуда не направляли',
 'доброго дня в каком общежитии поселят абитуриентов 090304',
 'результаты поступивших в магистратуру есть уже и списки',
 'спасибо и по военкомату надо ли сниматься с вучета',
 'очень понятно спасибо вам',
 'здравствуйте подскажите пожалуйста если в приказе в столбце сведения об общежитии стоит пометка да значит ли это что университет уже предоставил студенту место для проживания в общежитии',
 'урааааа',
 'понял спасибо',
 'сегодня приказ и что за статус набор завершён',
 'сегодня должны быть приказы а набор завершён значит набрали на это направление всех есть донабор по какимто направлениями в лк написано',
 'собрания будут в онлайн формате',
 'до какого числа будет идти прием документов на эти направления',
 'не планируете открывать прием согласий для людей которые ранее не подавали на эти направления подготовки',
 'эм где открыли',
 'но можно подать если при подаче документов до 29 июля указал направления на которые идет дополнительное зачисление',
 'доброго дня есть ли финальная информация об орг собраниях в частности по направлению 090303 очень интересует дата проведения спасибо',
 'таки ждать сегодня какуюнибудь информацию или теперь до понедельника просто в лк написано не позднее 20ого но пк то до 1800 работает',
 'ура сведения всё же появились большое спасибо',
 'а будут беседы в вк для первокурсников',
 'некоторые студенты уже создали группы своих направлений',
 'а где это можно найти',
 'в подслушано станкина есть специальное обсуждение также на стене есть информация',
 'а когда начинается обучение для перваков в станкине',
 'и заселение в общагу',
 'вопрос для тех кто отвечает за допнабор',
 'здравствуйте а если нет приписного свидетельства его почемуто не выдавали ранее',
 'а разве я успею до 20 возможно это сделать в самой москве для общаги же свидетельство не нужно',
 'ну то есть возможно его чуть позже принести',
 'было классно',
 'подскажите пожалуйста как ребёнка в школу юных записать',
 'доброе утро занятия сегодня будут в школе юных',
 'дети еще в школе до 15 странно вы время выбираете',
 'а мне нравится что в 12 молодцы',
 'вы не понимаете меня я не про день открытых дверей я про занятия в школе юных',
 'сбросьте пожалуйста контактный телефон школы юных',
 'вот она сила общения',
 'принял спасибо',
 'получается станкин и трудоустройством занимается',
 'друзья приглашаем школьников студентов колледжей и всех представителей наших партнеров бесплатно посетить выставку регистрируйся до 26012022 включительно',
 'это очень круто',
 'поддерживаю',
 'чем завершился процесс выведения орбитального блока на целевую геостационарную орбиту',
 'интересно в этом году обучение будет по wi fi или в аудиториях',
 'будем очень надеяться что обучение будет в аудиториях с wifi',
 'добры день ангара успешно доставила в космос разгонный блок персей с макетом спутника орбитальный блок в составе разгонного блока персей и габаритномассового макета полезной нагрузки отделился от третьей ступени тяжелой ракетыносителя ангараа5',
 'добрый день пуск ангары был в конце декабря 2021 г в настоящее время есть достоверная информация что разгонный блок с гмм полностью выполнили цели и задачи',
 'испытание космосом ангараа5 прошла успешно из этой информации модно сделать вывод что разгонный блок выполнил возложенные на него задачи это был заключительный тестовый пуск с макетом спутника впереди серийное производство для доставки на орбиту уже настоящих армейских и гражданских аппаратов',
 'здравствуйте когда начнутся вступительные экзамены',
 'могут ли иностранные абитуриенты сдавать экзамены онлайн',
 nan,
 'поздравляем победителей молодцы ребята',
 'смотреть с чатом интереснее',
 'это не только для москвы',
 'принять участие в мероприятиях проекта инженерные субботы могут только учащиеся школ г москвы',
 'промахнулась',
 'добрый день я хотел бы посетит унивнрситет на день открытых дверей как я могу это сделать',
 'добрый день александр для посещения университета в рамках дня открытых дверей необходимо пройти регистрацию на сайте [LINK]',
 'я окончил станкин в 2008 году хотел прийти с преподователями встретиться в столовую зайти чай с эклером выпить',
 'дает ли московская медаль за успехи в обучении допбаллы или только федеральная медаль имеет преимущества',
 'здравствуйте есть ли возможность получить доступ к фотографиям со дня открытых дверей 2304',
 'нарек гений',
 'нужна ли медсправка абитуриентам при подаче документов на поступление',
 'how can i enter russian preparatory caurse',
 'кто может быть в качестве сопровождающего и сопровождающий обязательно нужен',
 'добрый день а у вас есть альбом с фотографиями',
 'здравствуйте есть ли военный учебный центр военная кафедра в институте',
 'доброе время суток благодарю за информацию',
 'добрый день расскажите по направления 090301 090302 09',
 'а также 090303 и 090304 чем отличаются и где больше программирования',
 'здравствуйте прошу уточнить где располагаются учебные корпуса факультетов ивт прикладная информатика информсистемы и технологии',
 'спасибо за инфо',
 'подскажите пожалуйста а общежития всем иногородним предоставляется',
 'ещё вопрос об учебных планах на направления 090301 и 090302 где их можно посмотреть ссылку можно дать',
 'доброго дня как тут мало народу',
 'никак не могу найти учебные планы',
 '[LINK] это похоже на них но вроде бы не то',
 'спасибо остался вопрос об условиях предоставления общежития',
 'добрый день в общежитиях есть интернет или только свой мобильный как ребята готовятся к занятиям',
 'тоже интересует',
 'добрый день скажите пожалуйста если мы подаем документы через госуслуги цифровой аттестат приравнивается к бумажному можно бумажный оригинал будет привезти уже после зачисления',
 'здравствуйте на госуслугах стоит статус принято к рассмотрению когда появлюсь в ранжированных списках',
 'подскажите пожалуйста в перечне ид есть участие и или результаты участия в олимпиадах школьников не используемые для получения особых прав и или особого преимущества при поступлении на обучение по конкретным условиям поступления это про какие олимпиады идет речь',
 'есть еще участие и или результаты участия в олимпиадах и иных интеллектуальных и или творческих конкурсах физкультурных мероприятиях и спортивных мероприятиях проводимых в соответствии с частью 2 статьи 77 федерального закона 273 фз в целях выявления и поддержки лиц проявивших выдающиеся способности это про перечневые здесь говорится рсош я правильно понимаю',
 'здравствуйте подскажите как просмотреть стоимость платного обучения на сайте',
 '[LINK]',
 'это рсош и всош с перечнем можно ознакомиться здесь [LINK]',
 'здесь подразумеваются все остальные олимпиады',
 'а как участие в олимпиадах подтвердить за участие же грамоты не дают',
 'и за какие года нужно участие и результаты олимпиад',
 'первым делом наверное нужно уточнить можно получить 10 баллов максимум за индивидуальные достижения те при условии если у вас много ид получить можно всего 10 баллов дополнительно всё равно каким количеством они будут набраны за участие в олимпиадах дают как участнику свидетельство пришлите пожалуйста своё портфолио нам на почту и мы обязательно всё оценим ещё лучший вариант приехать лично подавать документы по адресу вадковский пер д 1 и взять с собой своё портфолио мы обязательно всё посмотрим и поможем во всем разобраться',
 'здравствуйте помогите пожалуйста где найти бланк заполнения заявления для поступления в станкин',
 'добрый день как надо заполнить строку в заявлении если поступаете на платную форму обучения',
 'добрый день каким способом вы подаете документы к нам',
 'электронным через сайт',
 '[LINK]',
 'запишитесь на zoom консультацию и мы вам поможем',
 'добрый день подскажите пожалуйста как быстро обрабатываются заявления поданные онлайн',
 'добрый день мы стараемся максимально быстро это делать но не всегда всё зависит только от нас',
 'всем абитуриентам дают общежитие',
 'в этом году увеличили количество мест в общежитии в прошлом году всем имеющим право и поступившим на бюджетную форму предоставили общежитие',
 'добрый вечер после выхода приказов о зачислении когда необходимо явиться в вуз для оформления студенческого билета и и тп',
 'обо всём мы дополнительно сообщим следите за новостями а пока держим',
 'здравствуйте когда появится возможность зайти в личный кабинет',
 'где подать согласие если через госуслуги заявление подавалось',
 'и почему несоответствие такое',
 'что значит обращение обратным письмом',
 'с днем рождения станкин',
 nan,
 'здравствуйте где можно посмотреть списки подавших документы',
 'нашёл разобрался',
 'добрый день как можно скорректировать сведения в личном кабинете анкетные если документы уже приняты',
 'здравствуйте что такое ваше место по согласиям',
 'положено ли общежитие если по целевому поступаешь',
 'скажите что за оператор у меня просят',
 'здравствуйте а через госуслуги можно тоже подать документы или непосредственно через ваш сайт',
 'добрый день подскажите пожалуйста если хотим прийти подать документы нам надо записываться на приём или можно просто прийти',
 'прошу вашей помощи мы подали документы в станкин но поняли что не хотим участвовать в конкурсе я звонила 5 раз писала просила убрать нас из списков действий никаких',
 'подскажите что мне нужно сделать что б нас все таки убрали из списков',
 'заявление написано на почту pk в личном кабинете удалились',
 'помогите птжалуйста',
 'добрый день подскажите пожалуйста если спецквота не будет выбрана полностью оставшиеся места перейдут в основные места если да то после какого числа это произойдёт',
 'можно ли согласие на зачисление подать очно в институте если заявление через госуслуги подавалосьтам сейчас сбой',
 'здравствуйте можно приезжайте подавайте приемная комиссия работает каждый день с 1000 до 1800',
 'можно ли в рейтинговых списках увидеть от какого именно предприятия целевая квота',
 'хотя бы количество мест и заявок',
 'добрый вечер а где можно посмотреть списки подавших документы',
 'добрый вечер конкурсные списки находятся на сайте приёмной комиссии [LINK]',
 'добрый день почему в списках нумерация задвоена и список получается не совсем ранжированный',
 'ведутся технические работы актуальная информация в лк [LINK]',
 'а есть какой то чат для абитуриентоа по поступлению где общаются например',
 'добрый день подскажите пожалуйста до скольки 03082022 будет работать приёмная комиссия',
 'утро доброе до 1800 но учтите абитуриент до этого времени должен предоставить документы необходимые для поступления а не придти до 1800',
 'можете скинуть направления и цены на платной основе',
 'с этой информацией вы можете ознакомиться на сайте приёмной комиссии [LINK]',
 'а как подать согласие в вуз',
 'в случае если вы не оставляли у нас оригинал документа об образовании рекомендуем вам как можно скорее это сделать к тому же лично вы сможете сразу подать и заявление о согласии на зачисление также пока нет очередей рекомендуем вам поторопиться так как сроки ограничены последний день приёма документов необходимых для зачисления то есть оригинала документа об образовании и заявления о согласии на зачисление 3 августа',
 'могу я самостоятельно явиться в вуз',
 'конечно можете',
 'когда будет настроена соответствующая сортировка внутри ранжированного списка',
 'здравствуйте получили письмо на электронную почту с предложением привезти оригинал и согласие лично подали заявление через епгу и планировали использовать возможность подать согласие и аттестат через епгу возникли какието сложности с документами учетная запись на госуслугах подтверждена результаты егэ прошлого 2021 года аттестат также подтвержден',
 'вам сообщили о возможности подать лично несмотря на статус который у вас на упомянутом сервисе тк всякое может быть и запасной вариант у вас должен быть',
 'можно пожалуйста ссылку',
 'на списки',
 'добрый день подскажите пожалуйста с какой периодичностью обновляются ранжированные списки',
 'это только 9 или 10 августа',
 'приказ о зачислении в приоритетную волну бви квоты выйдет послезавтра 30 июля приказ о зачислении в основной этап бюджет 9 августа',
 'а можете посказать до скольки будет работать очная приемка 3 августа',
 'добрый день подскажите во сколько выйдут приказы по приоритетному этапу',
 'до 1800 должна',
 'хотелось бы услышать мнение станкина',
 'спасибо а в связи с выходом приказов количество основных бюджетных мест в личном кабинете когда пересчитается',
 'здравствуйте скажите на робототехнике 77 бюджетных мест сколько из них уже занято целевиками квотниками и льготниками какое количество осталось для основного потока по баллам',
 'те количество оставшихся мест после квотниковльготников только в лк можно увидеть и узнать',
 'здравствуйте не могу подать согласие',
 'больше никуда его не подавал',
 'добрый день подскажите до какого часа завтра будет работать приёмная комиссия просто многие вузы продлили приём согласий до 2359 изза госуслуг',
 'можете подсказать сколько мест по направлениям бюджетным',
 'согласие на зачисление можете скинуть пожалуйста',
 'у вас на сайте вуза 85 бюджетных мест на направление 150305 а в лк абитуриена 60',
 'почему не 85',
 'вот именно',
 'я туда подал',
 'и я вылетел только что',
 'на 61',
 'я на 63',
 'я скачиваю pdf file согласия',
 'а он не ошибку выдаёт',
 'на сайте я на 63 месте а на ранжированных списках на 47 как это может быть',
 'возможно увеличение бюджетных мест завтра',
 'и на сколько',
 'ранжированные списки последний раз обновлялись в 11 утра это накануне стопа по приему невозможно оценить ситуацию',
 'добрый день хочу уточнить если абитуриент подал документы через госуслуги у него последняя возможность подать оригинал и согласие нажать кнопку через госуслуги тоже 0308 до 1800',
 'здравствуйте могу ли я забрать аттестат после 1800 если да то до скольких тогда',
 'добрый вечер приёмная комиссия сейчас не принимает звонки как уточнить статус заявления',
 'статус заявления можно уточнить в личном кабинете абитуриента приёмная комиссия завершила работу на сегодня',
 'мы подали через госуслуги',
 'там не прогружает',
 'и вы же приём продлили до 2359',
 'нет приём завершили в 1800',
 'почему на госуслугах написано в 2359',
 'если мы подали в 1740 оно будет принято',
 'мы не можем отвечать за сторонние сервисы согласно нашим правилам приёма мы были обязаны завершить принимать согласия в 1800',
 'а когда будет следующее обновление ранжированных списков на бакалавриатспециалитет у многих абитуриентов стоят галочки об оригинале согласия на зачисление но не стоят об оригинале документа об образовании они могут всётаки появиться позднее или их считать выбывшими из конкурса',
 'тоже интересует этот вопрос может надо уже брать документы и идти где доп зачисления начались или есть шанс пройти к вам',
 'уже многие вузы всё обновили и с гу разобрались',
 'то есть конкурс на зачисление ведется по одному фильтру списка согласие на зачисление галочка в поле документ об образовании не обязательна',
 'поясните пожалуйста абитуриенты с госуслуг для зачисления должны были подать либо оригинал аттестата либо аттестат в электронном виде через госуслуги вот эти электронные аттестаты не видны в конкурсных списках так это точно',
 'хм а ведь эти аттестаты _должны быть_ в конкурсных списках как предоставлен электронный документ',
 'не вижу никакой проблемы либо в этой же графе ставить галочку т к электронный приравнен к оригиналу либо вместо галочки ставить оригинал электронный а сейчас введены в заблуждение многие абитуриенты которые не видели и соответственно не могли учесть абитуриентов подавших документы с госуслуг',
 'а вы завтра до скольки работаете',
 'добрый день а во сколько будут приказы 9 августа',
 'и ещё вопрос ранжированные списки ещё будут обновляться до 9 числа',
 'здравствуйте а в личном кабинете абитуриента будет както отражена информация о зачислении',
 'добрый день есть ли предположительно время публикации приказа о зачислении',
 'очень волнуемся что до сих пор не учли наше письмо в почте по поводу общежития',
 'приятного аппетита ждем приказ',
 'здравствуйте а где можно будет найти информацию по поводу общежития',
 'но ведь там ничего нет',
 'или позже информация будет',
 'ура',
 'спасибо',
 'совсем скоро начало студенческих деньков так ещё и после школьных начинаю уже скучать по школе',
 'если уже есть карта сбера наверное нет необходимости заводить еще одну',
 'отлично а это когда будет',
 'спасибо',
 'добрый день скажите пожалуйста а нужно выбирать профиль на 270304',
 'когда заселение в общежитие где узнать информациюнадо брать билеты нужна ли доверенность нотариальная если ребенку нет 18 лет',
 'до подачи заявления в приёмной комиссии уверяли что мест в общежитиях станкина именно станкина всем хватит начались пугалки про малое количество мест и заселение в какието кузьминки где правда',
 'после шести можно забрать аттестат',
 'в личном кабинете абитуриента написана вся информация',
 'нужно завести другой личный кабинет в лк абитуриента нет информации',
 'то есть общежитие не в кузьминках будет',
 'кому можно позвонитьнаписать чтобы две подруги поступившие на одну специальность при распределении оказались в одной группе',
 'добрый день а если я приеду 31 августа мне достанется нормальная комната в общежитии и достанется ли вообще',
 'здравствуйте приписное свидетельство обязательно нужно или можно позже принести',
 'когда можно узнать по какому адресу находится общежитие',
 'здравствуйте какие направления заселяют в данное общежитие',

In [48]:
len(texts)

58197

In [49]:
df_preprocessed['text_preprocessed'] = texts

In [50]:
df_preprocessed.head()

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
0,Добрый день! Отличается ли перечень необходимы...,0,0,0,0,0,0,83,0.024096,добрый день отличается ли перечень необходимых...
1,Узбекистан. Рассматриваются обе формы,0,0,0,0,0,0,37,0.054054,узбекистан рассматриваются обе формы
2,"Здравствуйте, а как проходит поступление после...",0,0,0,0,0,0,147,0.040816,здравствуйте а как проходит поступление после ...
3,"Здравствуйте, а когда будет день открытых двер...",0,0,0,0,0,0,62,0.016129,здравствуйте а когда будет день открытых двере...
4,"Здравствуйте, необходимо для посещения дня отк...",0,0,0,0,0,0,82,0.012195,здравствуйте необходимо для посещения дня откр...

In [51]:
df_preprocessed.info()

<class 'pandas.DataFrame'>
RangeIndex: 58197 entries, 0 to 58196
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   text               58197 non-null  str
 1   label              58197 non-null  int64
 2   emojis             58197 non-null  int64
 3   newlines           58197 non-null  int64
 4   whitespaces        58197 non-null  int64
 5   links              58197 non-null  int64
 6   tags               58197 non-null  int64
 7   length             58197 non-null  int64
 8   capital_ratio      58197 non-null  float64
 9   text_preprocessed  58067 non-null  str
dtypes: float64(1), int64(7), str(2)
memory usage: 4.4 MB

### Удаление лишних строк

In [52]:
sum(df_preprocessed.isnull().sum(axis = 1))

130

In [53]:
df_preprocessed.dropna(subset=['text_preprocessed'], inplace=True)

In [54]:
df_preprocessed.info()

<class 'pandas.DataFrame'>
Index: 58067 entries, 0 to 58196
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   text               58067 non-null  str
 1   label              58067 non-null  int64
 2   emojis             58067 non-null  int64
 3   newlines           58067 non-null  int64
 4   whitespaces        58067 non-null  int64
 5   links              58067 non-null  int64
 6   tags               58067 non-null  int64
 7   length             58067 non-null  int64
 8   capital_ratio      58067 non-null  float64
 9   text_preprocessed  58067 non-null  str
dtypes: float64(1), int64(7), str(2)
memory usage: 4.9 MB

In [55]:
count_zero = df_preprocessed[df_preprocessed['label'] == 0].shape[0]

In [56]:
count_zero

33601

In [57]:
count_one = df_preprocessed[df_preprocessed['label'] == 1].shape[0]

In [58]:
count_one

24466

Итого мы получили 58067 строк, из которых:
- 33601 чистых сообщений
- 24466 сообщений, помеченных как спам

### Выявление корреляции между новыми параметрами и целевой переменной

Количество эмодзи действительно может влиять на результативность модели

In [59]:
df_preprocessed.sort_values('emojis', ascending=False)

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
37665,🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸<br>🌸🌸🌸🌸🌸🍋🍋🌸🌸🌸🍋🍋🌸🌸🌸🌸🌸\n🌸🌸🌸🌸🍋🍋...,1,466,38,19,1,0,1082,0.060074,br retention manager горячий трафик ру много с...
49375,СБЕРБАНК КАРТА 💳💳 АЛАМ<br>\n💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵...,1,424,203,107,0,0,3232,0.427290,сбербанк карта аламbr сбербанк карта алам сбер...
38796,🔥ЖИДКОСТИ🔥<br>😎БОЛЕЕ 5000 ДОВОЛЬНЫХ КЛИЕНТОВ😎\...,1,356,169,16,0,0,3039,0.333662,жидкостиbrболее 5000 довольных клиентов blood ...
35607,🔺SALES MANAGER🔺<br>♦️МЕНЕДЖЕР ПО ПРОДАЖАМ♦️\n\...,1,319,82,30,0,0,2468,0.451378,sales managerbrменеджер по продажам киев оболо...
56149,😤😤😤😤 <br>\n😤😤😤😤😤\n\n🟣БЕРЕМ РЕБЯТ С ОПЫТОМ И...,1,267,129,47,0,0,2450,0.436327,br берем ребят с опытом и без не ставим дедлай...
...,...,...,...,...,...,...,...,...,...,...
58192,"Лень закаляет характер, если вспомнить, скольк...",1,0,0,0,0,0,83,0.012048,лень закаляет характер если вспомнить сколько ...
58193,Я гриб. Подскажите мне полагается общежитие?,1,0,0,0,0,0,44,0.045455,я гриб подскажите мне полагается общежитие
58194,"Надо уметь закрывать скучную книгу, уходить с ...",1,0,0,0,0,0,108,0.009259,надо уметь закрывать скучную книгу уходить с п...
16988,А нет,0,0,0,0,0,0,5,0.200000,а нет
58181,Окружающие люди отлично понимают твою ценность...,1,0,0,0,0,0,92,0.021739,окружающие люди отлично понимают твою ценность...

Количество символов новой строки, к сожалению, не вступает в закономерность

In [60]:
df_preprocessed.sort_values('newlines', ascending=False)

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
34423,"ʙᥴᥱⲙ ᤋдρᥲʙᥴᴛʙуᥔᴛᥱ ,<br>ᥙ ϶ᴛ᧐ нᥲδ᧐ρ ʙ᧐ ɸ᧘уд\n""н...",1,81,236,82,0,0,2042,0.056317,ʙᥴᥱⲙ ᤋдρᥲʙᥴᴛʙуᥔᴛᥱ brᥙ ᴛ᧐ нᥲδ᧐ρ ʙ᧐ ɸ᧘уд нᥱɸᥙκ᧐ρ...
48569,🔫🔫🔫 🔫🔫🔫🔫🔫<br>\n\n🥶🥶🥶 \n\n\n⭐𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖...,1,82,229,125,0,4,2836,0.362482,br 𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖𝗥𝗘𝗘𝗡 1 𝗠𝗢𝗡𝗧𝗛 99ɪɴʀ2ᴜsᴅ 3 𝗠𝗢𝗡...
46806,🔫🔫🔫 🔫🔫🔫🔫🔫<br>\n\n🥶🥶🥶 \n\n\n⭐𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖...,1,82,229,125,0,3,2821,0.363701,br 𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖𝗥𝗘𝗘𝗡 1 𝗠𝗢𝗡𝗧𝗛 99ɪɴʀ2ᴜsᴅ 3 𝗠𝗢𝗡...
45560,🔫🔫🔫 🔫🔫🔫🔫🔫<br>\n\n🥶🥶🥶 \n\n\n⭐𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖...,1,82,229,125,0,3,2820,0.363830,br 𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖𝗥𝗘𝗘𝗡 1 𝗠𝗢𝗡𝗧𝗛 99ɪɴʀ2ᴜsᴅ 3 𝗠𝗢𝗡...
51092,🔠🔠🔠🔠🔠 🔠🔠🔠🔠🔠<br>\n\n🥶🥶🥶 \n\n\n⭐𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣...,1,84,228,125,0,3,2829,0.360551,br 𝗡𝗘𝗧𝗙𝗟𝗜𝗫 𝗣𝗥𝗜𝗩 𝗦𝗖𝗥𝗘𝗘𝗡 1 𝗠𝗢𝗡𝗧𝗛 99ɪɴʀ2ᴜsᴅ 3 𝗠𝗢𝗡...
...,...,...,...,...,...,...,...,...,...,...
6,Лучшая специальность! Жаль с моими баллами не ...,0,0,0,0,0,0,53,0.037736,лучшая специальность жаль с моими баллами не п...
5,"Добрый день! Да, необходимо пройти быструю рег...",0,0,0,0,1,0,91,0.021978,добрый день да необходимо пройти быструю регис...
4,"Здравствуйте, необходимо для посещения дня отк...",0,0,0,0,0,0,82,0.012195,здравствуйте необходимо для посещения дня откр...
3,"Здравствуйте, а когда будет день открытых двер...",0,0,0,0,0,0,62,0.016129,здравствуйте а когда будет день открытых двере...
2,"Здравствуйте, а как проходит поступление после...",0,0,0,0,0,0,147,0.040816,здравствуйте а как проходит поступление после ...

Количество пробелов тоже может влиять на результативность модели

In [61]:
df_preprocessed.sort_values('whitespaces', ascending=False)

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
50956,Занимаемcя поставкой теxники Sаmsung из ОАЭ🇦🇪 ...,1,93,182,172,5,0,2464,0.099432,занимаемcя поставкой теxники sаmsung из оаэ br...
47350,🤖 П р о в е р ь д е в у ш е к ...,1,12,21,166,0,4,637,0.043956,п р о в е р ь д е в у ш е к н а и н т и м н ы ...
47254,И н т и м к и с п о м о щ ь...,1,12,15,162,0,4,635,0.037795,и н т и м к и с п о м о щ ь ю и и br н о в ы е...
45703,▬▬▬▬▬▬▬▬▬▬▬▬▬▬<br>\n🔰𝗢𝗧𝗧 𝗣𝗟𝗔𝗧𝗙𝗢𝗥𝗠𝗦 🔰\n\n➜ NET...,1,56,181,140,0,0,2685,0.557542,br 𝗢𝗧𝗧 𝗣𝗟𝗔𝗧𝗙𝗢𝗥𝗠𝗦 netflix crack netflix 3 rd pa...
49008,💔🔠🔠🔠 🔠🔠🔠🔠🔠🔠🔠🔠 💔<br>\n⚡ NETFLIX CRACK \n⚡ NETF...,1,165,182,136,0,0,2823,0.552604,br netflix crack netflix 3 rd party netflix pr...
...,...,...,...,...,...,...,...,...,...,...
12,"А когда будут данные , о зачислении в магистра...",0,0,0,0,0,0,51,0.019608,а когда будут данные о зачислении в магистратуру
11,Вопрос к поступающим абитуриентам: какая ориен...,0,0,0,0,0,0,573,0.026178,вопрос к поступающим абитуриентам какая ориент...
10,"Подскажите, где найти ранжированные списки пос...",0,0,0,0,0,0,87,0.011494,подскажите где найти ранжированные списки пост...
9,"теперь увидел, спасибо. а как часто списки обн...",0,0,0,0,0,0,55,0.000000,теперь увидел спасибо а как часто списки обнов...
8,Здравствуйте. Не смог найти списки поступающих...,0,0,0,0,0,0,85,0.047059,здравствуйте не смог найти списки поступающих ...

Количество ссылок тоже может влиять на результативность модели

In [62]:
df_preprocessed.sort_values('links', ascending=False)

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
45247,"Completely FREE,crypto earning,NO deposit,NO i...",1,0,103,0,103,0,3928,0.023931,completely freecrypto earningno depositno inve...
45878,"Completely FREE,crypto earning,NO deposit,NO i...",1,0,103,0,103,0,3956,0.026542,completely freecrypto earningno depositno inve...
45127,"Completely FREE,crypto earning,NO deposit,NO i...",1,0,101,0,101,0,3864,0.024327,completely freecrypto earningno depositno inve...
46055,"Completely FREE,crypto earning,NO deposit,NO i...",1,0,98,0,98,0,3841,0.030982,completely freecrypto earningno depositno inve...
46054,https://bnbhs.com/ref/193822319366<br>https://...,1,0,87,0,87,0,3970,0.091436,[LINK] [LINK] [LINK] [LINK] [LINK] [LINK] [LIN...
...,...,...,...,...,...,...,...,...,...,...
58192,"Лень закаляет характер, если вспомнить, скольк...",1,0,0,0,0,0,83,0.012048,лень закаляет характер если вспомнить сколько ...
58193,Я гриб. Подскажите мне полагается общежитие?,1,0,0,0,0,0,44,0.045455,я гриб подскажите мне полагается общежитие
58194,"Надо уметь закрывать скучную книгу, уходить с ...",1,0,0,0,0,0,108,0.009259,надо уметь закрывать скучную книгу уходить с п...
58195,"⚡️⚡️⚡️\n\nДорогие родители, напоминаем вам, чт...",1,1,10,5,0,0,599,0.033389,дорогие родители напоминаем вам что ровно чере...
58181,Окружающие люди отлично понимают твою ценность...,1,0,0,0,0,0,92,0.021739,окружающие люди отлично понимают твою ценность...

Количество тэгов тоже может влиять на результативность модели

In [63]:
df_preprocessed.sort_values('tags', ascending=False)

,text,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio,text_preprocessed
44356,✔️ SORGU PANELİ SATIN ALMAK İÇİN ✔️<br>\n\n\n@...,1,13,97,36,0,91,1340,0.166418,sorgu paneli satin almak için br [TAG] [TAG] [...
46040,💠SHARE YOUR LINK💠<br>\n𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫...,1,2,91,93,2,81,1994,0.130893,share your linkbr 𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞 [LI...
48306,🌟SHARE YOUR LINK🌟<br>\n𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫...,1,2,88,92,2,80,1925,0.104416,share your linkbr 𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞 [LI...
48311,👑👑SHARE LINK👑👑<br>\n𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞.-...,1,4,88,92,2,80,1924,0.102911,share linkbr 𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞 [LINK] 1...
48305,🌞🌞SHARE🌞🌞<br>\n𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞.- \nht...,1,4,88,92,2,80,1929,0.101089,sharebr 𝟖𝟎 𝐠𝐫𝐨𝐮𝐩𝐬 𝐟𝐨𝐫 𝐥𝐢𝐧𝐤 𝐬𝐡𝐚𝐫𝐞 [LINK] 1 [TAG...
...,...,...,...,...,...,...,...,...,...,...
6,Лучшая специальность! Жаль с моими баллами не ...,0,0,0,0,0,0,53,0.037736,лучшая специальность жаль с моими баллами не п...
7,"Было бы неплохо, если бы прикладывались ссылки...",0,0,0,0,0,0,84,0.011905,было бы неплохо если бы прикладывались ссылки ...
8,Здравствуйте. Не смог найти списки поступающих...,0,0,0,0,0,0,85,0.047059,здравствуйте не смог найти списки поступающих ...
9,"теперь увидел, спасибо. а как часто списки обн...",0,0,0,0,0,0,55,0.000000,теперь увидел спасибо а как часто списки обнов...
10,"Подскажите, где найти ранжированные списки пос...",0,0,0,0,0,0,87,0.011494,подскажите где найти ранжированные списки пост...

Чтобы проверить корреляцию – нужно оставить в таблице только числовые значения

In [64]:
df_corr = deepcopy(df_preprocessed)
del df_corr['text']
del df_corr['text_preprocessed']

Итоги корреляции:
- **Эмодзи**, **лишние пробелы**, **переносы строк** оказывают **умеренное влияние** на предсказание класса (`label`).
- **Ссылки** и **тэги** имеют **слабую корреляцию с целевой переменной**, но их использование может быть полезно в сочетании с другими признаками.

In [65]:
df_corr.corr()

,label,emojis,newlines,whitespaces,links,tags,length,capital_ratio
label,1.000000,0.401203,0.451962,0.418002,0.181270,0.214093,0.492412,0.243905
emojis,0.401203,1.000000,0.785998,0.718008,0.383296,0.244083,0.695457,0.193804
newlines,0.451962,0.785998,1.000000,0.899793,0.510780,0.330570,0.888727,0.215513
whitespaces,0.418002,0.718008,0.899793,1.000000,0.406156,0.325550,0.794848,0.185351
links,0.181270,0.383296,0.510780,0.406156,1.000000,0.053221,0.507910,0.054751
tags,0.214093,0.244083,0.330570,0.325550,0.053221,1.000000,0.334439,0.108455
length,0.492412,0.695457,0.888727,0.794848,0.507910,0.334439,1.000000,0.158230
capital_ratio,0.243905,0.193804,0.215513,0.185351,0.054751,0.108455,0.158230,1.000000

## Сохранение данных

In [66]:
df_preprocessed.to_csv('../data/preprocessed.csv')